# Generated by Django 3.2.25 on 2024-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20240308_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
